-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 13:37:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema db_untec_biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_untec_biblioteca` ;

-- -----------------------------------------------------
-- Schema db_untec_biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_untec_biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
SHOW WARNINGS;
USE `db_untec_biblioteca` ;

-- -----------------------------------------------------
-- Table `db_untec_biblioteca`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_untec_biblioteca`.`libro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `db_untec_biblioteca`.`libro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `editorial` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  `isbn` VARCHAR(20) NOT NULL,
  `anio_publicacion` INT(11) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT '',
  `img_url` VARCHAR(255) NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `db_untec_biblioteca`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_untec_biblioteca`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `db_untec_biblioteca`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `passwrd` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL DEFAULT 'ALUMNO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `db_untec_biblioteca`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_untec_biblioteca`.`prestamo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `db_untec_biblioteca`.`prestamo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_libro` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_tope` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'PRESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_prestamo_libro` (`id_libro` ASC) VISIBLE,
  INDEX `fk_prestamo_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `db_untec_biblioteca`.`libro` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_prestamo_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_untec_biblioteca`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
